## This file is auto-generated (at 2007-07-19T12:15:40Z).
## Do not edit by hand!
use strict;

package Char::Class::Kana;
our $VERSION = '1.02';

use Exporter;
use vars qw(@EXPORT_OK @ISA $VERSION);
@ISA = qw(Exporter);

=head1 NAME

Char::Class::Kana - Regular Expression Character Classes - C<Kana>


=cut

sub import ($;@) {
  my ($self, @sub) = (shift, @_);
  for (@sub) {
    no strict 'refs';
    *{'main::'.$_} = \&{$_};
  }
  $Exporter::ExportLevel = 1;
  $self->SUPER::import (@_);
  $Exporter::ExportLevel = 0;
}

@EXPORT_OK = qw(InKanaAll InKanaDigraph InKanaHatsuon InKanaSeion InKanaSemiVoiced InKanaSmall InKanaVoiced);

sub InKanaAll {
<<EOH;
3041	3096	
309D	309F	
30A1	30FA	
30FD	30FF	
31F0	31FF	
3099	309C	
3031	3035	
303B
30FC
EOH
}

sub InKanaDigraph {
<<EOH;
309F
30FF
EOH
}

sub InKanaHatsuon {
<<EOH;
3098
30F3
EOH
}

sub InKanaSeion {
<<EOH;
3042
3044
3046
3048
304A
304B
304D
304F
3051
3053
3055
3057
3059
305B
305D
305F
3061
3064
3066
3068
306A
306B
306C
306D
306E
306F
3072
3075
3078
307B
307E
307F
3080
3081
3082
3084
3086
3088
3089
308A
308B
308C
308D
308F
3090
3091
3092
30A2
30A4
30A6
30A8
30AA
30AB
30AD
30AF
30B1
30B3
30B5
30B7
30B9
30BB
30BD
30BF
30C1
30C4
30C6
30C8
30CA
30CB
30CC
30CD
30CE
30CF
30D2
30D5
30D8
30DB
30DE
30DF
30E0
30E1
30E2
30E4
30E6
30E8
30E9
30EA
30EB
30EC
30ED
30EF
30F0
30F1
30F2
EOH
}

sub InKanaSemiVoiced {
<<EOH;
3071
3074
3077
307A
307D
30D1
30D4
30D7
30DA
30DD
EOH
}

sub InKanaSmall {
<<EOH;
3041
3043
3045
3047
3049
3063
3083
3085
3087
308E
3095
3096
30A1
30A3
30A5
30A7
30A9
30C3
30E3
30E5
30E7
30EE
30F5
30F6
31F0
31F1
31F2
31F3
31F4
31F5
31F6
31F7
31F8
31F9
31FA
31FB
31FC
31FD
31FE
31FF
EOH
}

sub InKanaVoiced {
<<EOH;
304C
304E
3050
3052
3054
3056
3058
305A
305C
305E
3060
3062
3065
3067
3069
3070
3073
3076
3079
307C
3094
30AC
30AE
30B0
30B2
30B4
30B6
30B8
30BA
30BC
30BE
30C0
30C2
30C5
30C7
30C9
30D0
30D3
30D6
30D9
30DC
30F4
30F7
30F8
30F9
30FA
EOH
}

=head1 COLLECTION NAMES

=over 4

=item C<InKanaAll>

=item C<InKanaDigraph>

=item C<InKanaHatsuon>

=item C<InKanaSeion>

=item C<InKanaSemiVoiced>

=item C<InKanaSmall>

=item C<InKanaVoiced>

=back

=cut


=head1 EXAMPLE

 use Char::Class::Kana;
 if ($s =~ /\p{InSeion}/) {
   print "Match!\n";
 }

=head1 LICENSE

Copyright 2007 Wakaba <w@suika.fam.cx>

This library and the library generated by it is free software;
you can redistribute them and/or modify them under the same
terms as Perl itself.

=cut

1;
### Kana.pm ends here
